apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tododb/tododb-statset.yaml
  - kube-todo/kube-todo-svc.yaml
  - kube-todo/kube-todo-depl.yaml

images:
  - name: PROJECT/IMAGE
    newName: deeq/kube-todo:latest