apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-uuid
spec:
  selector:
    matchLabels:
      app: print-uuid
  template:
    metadata:
      labels:
        app: print-uuid
    spec:
      containers:
      - name: print-uuid
        image: deeq/print_uuid
