apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-todo-db-pvc
  namespace: project
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
