apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-todo-db-pv
  namespace: project
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  local:
    path: /tmp/kube-todo/DB
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k3d-k3s-default-agent-0
