apiVersion: v1
kind: Service
metadata:
  name: kube-todo-service
  namespace: project
spec:
  type: LoadBalancer
  selector:
    app: kube-todo
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000