apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-todo
  namespace: project
spec:
  selector:
    matchLabels:
      app: kube-todo
  template:
    metadata:
      labels:
        app: kube-todo
    spec:
      containers:
      - name: kube-todo
        image: PROJECT/IMAGE
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-conf
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kube-todo-secret
                key: POSTGRES_PASSWORD


