apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kube-todo
  namespace: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-todo
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: cpu-rate
  template:
    metadata:
      labels:
        app: kube-todo
    spec:
      volumes:
        - name: shared-image-db
          persistentVolumeClaim:
            claimName: kube-todo-db-pvc
        - name: shared-image-potd
          persistentVolumeClaim:
            claimName: kube-todo-potd-pvc
      containers:
      - name: kube-todo
        image: deeq/kube-todo:1.7
        volumeMounts:
          - mountPath: /app/DB
            name: shared-image-db
          - mountPath: /app/backend/potd
            name: shared-image-potd
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-conf
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kube-todo-secret
                key: POSTGRES_PASSWORD


