apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: exercises
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /tmp/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k3d-k3s-default-agent-0
