apiVersion: v1
kind: Service
metadata:
  name: pong-postgres-svc
  namespace: exercises
spec:
  ports:
  - port: 5432
    name: dbdata
  clusterIP: None
  selector:
    app: pong-postgres
  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pong-postgres-ss
  namespace: exercises
spec:
  selector:
    matchLabels:
      app: pong-postgres
  serviceName: pong-postgres-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: pong-postgres
    spec:
      containers:
      - name: pong-postgres
        image: deeq/pong-postgres:latest
        ports:
        - containerPort: 5432
          name: dbdata
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        envFrom:
        - configMapRef: 
            name: postgres-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi

