# Generated by Django 3.1.7 on 2021-04-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Potd',
        ),
    ]
