apiVersion: apps/v1
kind: Deployment
metadata:
  name: uuid-app-http
  namespace: exercises
spec:
  selector:
    matchLabels:
      app: uuid-app-http
  template:
    metadata:
      labels:
        app: uuid-app-http
    spec:
      containers:
      - name: uuid-app-http
        image: deeq/uuid-app-http:latest
        readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /healthz
               port: 8083
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: uuid-confmap
                key: message