apiVersion: v1
kind: Service
metadata:
  name: tododb-svc
  namespace: project
spec:
  ports:
  - port: 5432
    name: dbdata
  clusterIP: None
  selector:
    app: tododb
  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tododb-ss
  namespace: project
spec:
  selector:
    matchLabels:
      app: tododb
  serviceName: tododb-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: tododb
    spec:
      containers:
      - name: tododb
        image: postgres:latest
        ports:
        - containerPort: 5432
          name: dbdata
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        envFrom:
        - configMapRef: 
            name: tododb-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kube-todo-secret
                key: POSTGRES_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 500Mi

