name: Delete Application

on: [delete]

env:
  GKE_CLUSTER: dwk-kko
  GKE_ZONE: europe-north1-b
  IMAGE: kube-todo
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  delete-environment:
    name: Delete environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT_ID }}

      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      
      - name: Delete namespace
        run: |-
          echo "::set-env name=GITHUB_REF::${{ github.event.ref }}"
          GITHUB_REF=$(echo $GITHUB_REF | sed -e "s#refs/heads/##g")
          kubectl delete namespaces $GITHUB_REF